overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
            resolver_maps:
              - App\GraphQL\Resolver\MovieResolver
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
